#!/bin/sh

# $Ragnarok: install,v 1.2 2024/08/20 20:00:18 lecorbeau Exp $

VERSION="01"
FLAVOUR="bookworm"

/usr/bin/mmdebstrap --skip=check/empty --variant="minbase" \
	--components="main non-free-firmware" \
	--include="usrmerge ca-certificates oksh signify-openbsd less wget ed" \
	--hook-directory=hooks \
	"${FLAVOUR}" /mnt \
	"deb https://ragnarokos.github.io/base/deb/ ${VERSION} main" \
	"deb http://deb.debian.org/debian/ ${FLAVOUR} main non-free-firmware" \
	"deb http://security.debian.org/ ${FLAVOUR}-security main non-free-firmware" \
	"deb http://deb.debian.org/debian/ ${FLAVOUR}-updates main non-free-firmware"
