#!/bin/ksh

# Main installer script.
# $Ragnarok: ragnarok-install,v 1.2 2024/04/09 15:11:11 lecorbeau Exp $

# Parse config values
FLAVOUR=$(awk '/Flavour/ { print $3 }' install.conf)
VARIANT=$(awk '/Variant/ { print $3 }' install.conf)
COMPONENTS=$(awk '/Components/ { print $3 }' install.conf)

# mmdebstrap the system.
debstrap() {
	/usr/bin/mmdebstrap --variant="${VARIANT}" \
		--components="${COMPONENTS}" \
		--hook-directory=hooks/ \
		"${FLAVOUR}" /mnt \
		"deb https://ragnarokos.github.io/base/deb/ current main" \
		"deb https://ragnarokos.github.io/xserv/deb/ current main" \
		"deb http://deb.debian.org/debian/ bookworm main non-free-firmware" \
		"deb http://security.debian.org/ bookworm-security main non-free-firmware" \
		"deb http://deb.debian.org/debian/ bookworm-updates main non-free-firmware"
}

finish() {
	local _resp

	read -r _resp?"Installation complete. Type r (to reboot) or e (to exit and stay in the live session) then Return. "

	case "$_resp" in
		r)	loginctl reboot
			;;
		e)	exit 0
			;;
		*)	loginctl reboot
			;;
	esac
}

main() {
	debstrap
	finish
}

main 2>&1 | tee install.log
