#!/bin/ksh

# $Ragnarok$

. /lib/ragnarok-installer/funcs
. /lib/ragnarok-installer/lists

# Set colors
export NEWT_COLORS='
root=black,black
shadow=black,black
window=,black
border=white,black
title=white,black
textbox=white,black
button=black,white
checkbox=white,black
actcheckbox=black,white
compactbutton=white,black
entry=white,black
'

## Global Variables
FLAVOUR="bookworm"
VERSION="01"

## Functions

# Create the base system.
debstrap() {
	/usr/bin/mmdebstrap --variant=minbase \
		--components="main non-free-firmware" \
		--include="usrmerge ca-certificates oksh signify-openbsd less wget ed" \
		--hook-directory=/lib/ragnarok-installer/hooks \
		--skip=check/empty "${FLAVOUR}" /mnt \
		"deb https://ragnarokos.github.io/base/deb/ ${VERSION} main" \
		"deb http://deb.debian.org/debian/ ${FLAVOUR} main non-free-firmware" \
		"deb http://security.debian.org/ ${FLAVOUR}-security main non-free-firmware" \
		"deb http://deb.debian.org/debian/ ${FLAVOUR}-updates main non-free-firmware"
}

main() {
	/lib/ragnarok-installer/mkdisk
	debstrap
}
main
