#!/bin/sh

# $Ragnarok: postinst,v 1.5 2024/10/20 15:19:36 lecorbeau Exp $

set -e

# Fix permissions
/usr/bin/chmod 644 /lib/ragnarok-installer/funcs
/usr/bin/chown root:root /lib/ragnarok-installer/funcs
/usr/bin/chmod 755 /lib/ragnarok-installer/hooks/customize01.sh
/usr/bin/chmod 755 /lib/ragnarok-installer/hooks/customize02.sh
/usr/bin/chmod 755 /lib/ragnarok-installer/hooks/setup01.sh
/usr/bin/chown root:root /lib/ragnarok-installer/hooks/customize01.sh
/usr/bin/chown root:root /lib/ragnarok-installer/hooks/customize02.sh
/usr/bin/chown root:root /lib/ragnarok-installer/hooks/setup01.sh
/usr/bin/chmod 755 /usr/bin/afterinstall
/usr/bin/chmod 755 /usr/bin/mkconf
/usr/bin/chmod 755 /usr/bin/ragnarok-install
/usr/bin/chmod 755 /usr/bin/rstrap
/usr/bin/chmod 755 /usr/bin/setcons
/usr/bin/chmod 755 /usr/bin/setkb
/usr/bin/chmod 755 /usr/bin/setlocale
/usr/bin/chmod 755 /usr/bin/settz
/usr/bin/chown root:root /usr/bin/afterinstall
/usr/bin/chown root:root /usr/bin/mkconf
/usr/bin/chown root:root /usr/bin/ragnarok-install
/usr/bin/chown root:root /usr/bin/rstrap
/usr/bin/chown root:root /usr/bin/setcons
/usr/bin/chown root:root /usr/bin/setkb
/usr/bin/chown root:root /usr/bin/setlocale
/usr/bin/chown root:root /usr/bin/settz
/usr/bin/chmod 644 /usr/share/ragnarok-installer/lists/*
/usr/bin/chown root:root /usr/share/ragnarok-installer/lists/*

# Create the _installer user for the unpriv() function if it doesn't
# already exists.
if ! getent passwd _installer >/dev/null; then
	/usr/sbin/useradd --system --no-create-home --home /nonexistent \
		--shell=/usr/sbin/nologin _installer
fi
