#!/bin/ksh

# Configuring the console based on the locale chosen by the user.
# Credits to the d-i team for leading me in the right direction
# with console-setup.config.

. ../installer/lib/ragnarok-installer/funcs

CONF="install.conf"
_locale=$(get_val Locale "$CONF")

# Set the codeset
case "$_locale" in
	*KOI8*|*koi8*)
		CODESET=CyrKoi
		;;
	aa_*|af_*|an_*|ast_*|br_*|ca_*|da_*|de_*|en_*|es_*|et_*|eu_*|fi_*|fo_*|fr_*|gd_*|gl_*|gv_*|id_*|is_*|it_*|kl_*|kw_*|lg_*|ms_*|nb_*|nl_*|nn_*|oc_*|om_*|pt_*|sid_*|so_*|sq_*|st_*|sv_*|tl_*|tr_*|tt_*|uz_*|wa_*|xh_*|zu_*)
		CODESET=Lat15
		;;
	am_*|byn_*|gez_*|ti_*|tig_*)
		CODESET=Ethiopian
		;;
	ar_*|fa_*|ur_*)
		CODESET=Arabic
		;;
	az_*bs_*)
		CODESET=Uni3
		;;
	be_*|bg_*|mk_*|ru_*|sr_*|uk_*)
		CODESET=CyrSlav
		;;
	bn_*|gu_*|hi_*|ja_*|kn_*|ko_*|ml_*|mr_*|ne_*|pa_*|ta_*|te_*|zh_*)
		CODESET=unsupported
		;;
	cs_*|hr_*|hu_*|pl_*|ro_*|sk_*|sl_*)
		CODESET=Lat2
		;;
	cy_*|eo|eo_*|eo\@*|ga_*|mt_*)
		CODESET=Lat38
		;;
	el_*)
		CODESET=Greek
		;;
	he_*|iw_*|yi_*)
		CODESET=Hebrew
		;;
	hy_*)
		CODESET=Armenian
		;;
	ka_*)
		CODESET=Georgian
		;;
	lo_*)
		CODESET=Lao
		;;
	lt_*|lv_*|mi_*)
		CODESET=Lat7
		;;
	ky_*|mn_*|tg_*|uz_*\@cyrillic)
		CODESET=CyrAsia
		;;
	se_*)
		CODESET=Uni1
		;;
	th_*)
		CODESET=Thai
		;;
	vi_*)
		CODESET=Vietnamese
		;;
	*)	
		CODESET=guess
		;;
esac

if [[ $CODESET = unsupported ]]; then
	CODESET=guess
fi

# Set the font
case "$CODESET" in
	Arabic|CyrKoi|Uni1)
		FONTFACE=VGA
		;;
	Ethiopian)
		FONTFACE=Goha
		;;
	*)
		FONTFACE=Fixed
		;;
esac

if lsmod 2> /dev/null | grep -q speakup; then
	case "$CODESET" in
		CyrAsia|CyrSlav|Greek)
			CODESET="Full${CODESET}"
			;;
	esac
fi

# If $CODESET is Lat15, set the console font to spleen. We can only do
# it for Lat15 because it's the only one I know for sure will look good.
# If anyone wants to test it on other codesets, be my guess.
# NOTE: This should be done at the end of console-setup.
# NOTE 2: Only do this if xfonts is part of the selected sets because the
# spleen package pulls some X stuff and that should be avoided on systems
# that don't want X at all (even if the X stuff pulled is small). I will
# package the console font for spleen individually so that it can be added
# to the base system without pulling in any dependency.
if grep -q "xfonts" "$CONF"; then
	case "$CODESET" in
		Lat15)
			sed -i 's/FONTFACE/#&/' /mnt/etc/default/console-setup
			sed -i 's/FONTSIZE/#&/' /mnt/etc/default/console-setup
			printf '%s\n' 'FONT="spleen-8x16.psfu.gz' >> /mnt/etc/default/console-setup
			;;
	esac
fi

echo "$CODESET"
echo "$FONTFACE"
