#!/bin/ksh

# Main installer script.
# $Ragnarok: ragnarok-install,v 1.6 2024/04/19 15:58:25 lecorbeau Exp $

TMP=$(mktemp -d -p /tmp ragnarok-install.XXXXXXXXXX)
# Parse config values
CODENAME=$(awk '/Codename/ { print $3 }' install.conf)
FLAVOUR=$(awk '/Flavour/ { print $3 }' install.conf)
VARIANT=$(awk '/Variant/ { print $3 }' install.conf)
COMPONENTS=$(awk '/Components/ { print $3 }' install.conf)
MIRROR=$(awk '/Mirror/ { print $3 }' install.conf)
VERSION=$(awk 'Version/ { print $3 }' install.conf)
URL="${MIRROR}${VERSION}"

# Never download stuff off the internet as the root user.
# I take no credit for this function. All credit goes to
# Antoine Jacoutot, who wrote OpenBSD's syspatch(1).
unpriv() {
	local _file=$2 _ret=0 _user=_apt

	if [[ $1 == -f && -n ${_file} ]]; then
		# shellcheck disable=SC2188
		>${_file}
		chown "${_user}" "${_file}"
		chmod 0711 "${TMP}"
		shift 2
	fi
	(($# >= 1))

	su -s /bin/sh ${_user} -c "$@" || _ret=$?

	[[ -n ${_file} ]] && chown root "${_file}"

	return ${_ret}
}

# Download the tarball
get_tarball() {
	local _file="miniroot${VERSION}.tgz"

	printf '%s\n' "Fetching ${_file}..."
	unpriv -f "${TMP}/${_file}" "wget -q --show-progress -P ${TMP} -O ${_file} ${URL}/${_file}"
}

# Extract miniroot.tgz
extract() {
	tar xzpvf "${TMP}/miniroot${VERSION}.tgz" --xattrs --xattrs-include='*' --numeric-owner -C /mnt
}

finish() {
	local _resp

	read -r _resp?"Installation complete. Type r (to reboot) or e (to exit and stay in the live session) then Return. "

	case "$_resp" in
		r)	loginctl reboot
			;;
		e)	exit 0
			;;
		*)	loginctl reboot
			;;
	esac
}

main() {
	get_tarball
	extract
	finish
}

main 2>&1 | tee install.log
